---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
reclaimPolicy: {{ .Values.reclaimPolicy }}
parameters:
  server: {{ .Values.server }}
  share: {{ .Values.share }}
  #    subDir:
  mountPermissions: "0"
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
#    csi.storage.k8s.io/provisioner-secret-name: "mount-options"
#    csi.storage.k8s.io/provisioner-secret-namespace: "default"
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2