# Install wg on host to use this: apt install wireguard wireguard-tools
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netclient
  labels:
    app: netclient
spec:
  selector:
    matchLabels:
      app: netclient
  template:
    metadata:
      labels:
        app: netclient
    spec:
      hostNetwork: true
      containers:
      - name: netclient
        image: gravitl/netclient:latest
        env:
        - name: NETCLIENT_ROAMING
          value: "no"
        - name: NETCLIENT_PORT
          value: "51821"
        - name: NETCLIENT_IS_STATIC
          value: "yes"
        - name: NETCLIENT_ENDPOINT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: netmaker-client-token
              key: token
        volumeMounts:
        - mountPath: /etc/netclient
          name: etc-netclient
        - mountPath: /var/log
          name: logs-netclient
          subPath: netclient.log
        - mountPath: /usr/bin/wg
          name: wg
        securityContext:
          privileged: true
      volumes:
      - hostPath:
          path: /etc/netclient
          type: DirectoryOrCreate
        name: etc-netclient
      - hostPath:
          path: /etc/netclient/logs
          type: DirectoryOrCreate
        name: logs-netclient
      - hostPath:
          path: /usr/bin/wg
          type: File
        name: wg
