app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/linuxserver/plex
            tag: latest
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: latest
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: latest
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: latest
        overseerr:
          image:
            repository: sctx/overseerr
            tag: latest
        wizarr:
          image:
            repository: ghcr.io/wizarrrr/wizarr
            tag: latest
  service:
    main:
      ports:
        http:
          port: 32400
          protocol: HTTP
        prowlarr:
          port: 9696
          protocol: HTTP
        radarr:
          port: 7878
          protocol: HTTP
        sonarr:
          port: 8989
          protocol: HTTP
        overseerr:
          port: 5055
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: ssl-prod
      hosts:
        - host: &plexHost plex-test.galactica.host
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
        - host: &transmissionHost transmission.galactica.host
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: transmission
        - host: &prowlarrHost prowlarr.galactica.host
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: prowlarr
        - host: &radarrHost radarr.galactica.host
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: radarr
        - host: &sonarrHost sonarr.galactica.host
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: sonarr
        - host: &overseerrHost requests-test.galactica.host
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: overseerr
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *plexHost
            - *transmissionHost
            - *prowlarrHost
            - *radarrHost
            - *sonarrHost
            - *overseerrHost
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        main:
          plex:
            - path: /config
              subPath: plex/config
          prowlarr:
            - path: /config
              subPath: prowlarr/config
          radarr:
            - path: /config
              subPath: radarr/config
          sonarr:
            - path: /config
              subPath: sonarr/config
          overseerr:
            - path: /app/config
              subPath: overseerr/config
