# TODO create user and access token
# users:
#   - name: renovate
#     fullName: Renovate
#     email: bot@renovateapp.com
#     tokenSecretRef: renovate-secret # ???
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: homelab
    owner: ops
    private: false
    migrate:
      source: https://github.com/adamazoulay/homelab-proxmox-k8s
      mirror: true
#  - name: blog
#    owner: adamazoulay
#    migrate:
#      source: https://github.com/adamazoulay/blog
#      mirror: true
#  - name: backstage
#    owner: adamazoulay
#    migrate:
#      source: https://github.com/adamazoulay/backstage
#      mirror: true
