{{- range .Values.services }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .name }}-external-ip
  labels:
    kubernetes.io/service-name: {{ .name }}-external
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: {{ .port }}
endpoints:
  - addresses:
      - {{ .address }}
{{- end}}