apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opnsense
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "opnsense.galactica.host"
      secretName: "opnsense-tls-certificate"
  rules:
    - host: "opnsense.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: opnsense-external
                port:
                  number: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: opnsense-external
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  clusterIP: None
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: opnsense-external-ip
  labels:
    kubernetes.io/service-name: opnsense-external
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: 8443
endpoints:
  - addresses:
      - "192.168.0.1"