apiVersion: v1
kind: Service
metadata:
  name: proxmox-external
spec:
  ports:
    - name: proxmox
      port: 8006
      protocol: TCP
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-external-ip
subsets:
  - addresses:
      - ip: 192.168.0.11
    ports:
      - name: proxmox
        port: 8006
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox
  labels:
    app.kubernetes.io/instance: proxmox
    app.kubernetes.io/name: proxmox
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "proxmox.galactica.host"
      secretName: "proxmox-tls-certificate"
  rules:
    - host: "proxmox.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: proxmox-external
                port:
                  number: 8006