apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "proxmox.galactica.host"
      secretName: "proxmox-tls-certificate"
  rules:
    - host: "proxmox.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: proxmox-external
                port:
                  number: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-external
spec:
  ports:
    - name: https
      port: 8006
      protocol: TCP
      targetPort: 8006
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: proxmox-external-ip
  labels:
    kubernetes.io/service-name: proxmox-external
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: 8006
endpoints:
  - addresses:
      - "192.168.0.10"