gitea:
  replicaCount: 1

  persistence:
    claimName: gitea-shared-storage
    size: 25Gi

  postgresql-ha:
    enabled: false

  redis-cluster:
    enabled: false

  postgresql:
    volumePermissions:
      enabled: false
      image:
        registry: docker.io
        repository: bitnami/os-shell
        tag: 12-debian-12-r19
        digest: ""
        pullPolicy: IfNotPresent
        pullSecrets: [ ]
      resourcesPreset: "nano"
      resources: { }
      containerSecurityContext:
        seLinuxOptions: { }
        runAsUser: 1000
        runAsGroup: 100
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault

    image:
      debug: true
    enabled: true
    persistence:
      size: 10Gi

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host git.galactica.host
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.galactica.host
        OFFLINE_MODE: true
      repository:
        DISABLED_REPO_UNITS: repo.wiki,repo.projects,repo.packages
        DISABLE_STARS: true
        DEFAULT_BRANCH: main
      # TODO it's not reading the username from Dex correctly for now, related issues:
      # https://github.com/go-gitea/gitea/issues/25725
      # https://github.com/go-gitea/gitea/issues/24957
      # oauth2_client:
      #   ENABLE_AUTO_REGISTRATION: true
      #   USERNAME: userid
      service.explore:
        DISABLE_USERS_PAGE: true
      actions:
        ENABLED: false
      webhook:
        ALLOWED_HOST_LIST: private
