---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: gitea-pg-pvc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0700
    - file_mode=0700
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    # TODO: move these to values
    volumeHandle: //192.168.0.11/homelab-k8s#gitea-pg-pvc#gitea-pg-pvc
    volumeAttributes:
      source: //192.168.0.11/homelab-k8s
    nodeStageSecretRef:
      name: smbcreds
      namespace: kube-system