---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  type: ClusterIP
  ports:
    - port: 6767
      targetPort: 6767
      protocol: TCP
      name: bazarr
  selector:
    app.kubernetes.io/component: bazarr
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/name: bazarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/component: bazarr
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/name: bazarr
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: bazarr
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/instance: bazarr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: bazarr
        app.kubernetes.io/instance: bazarr
        app.kubernetes.io/name: bazarr
    spec:
      enableServiceLinks: true
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: linuxserver/bazarr:latest
          name: bazarr
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: bazarr/config
            - mountPath: /data
              name: tank-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media-stack-data-local
        - name: tank-data
          persistentVolumeClaim:
            claimName: pvc-tank-data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/name: bazarr
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "bazarr.galactica.host"
      secretName: "bazarr-tls-certificate"
  rules:
    - host: "bazarr.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: bazarr
                port:
                  number: 6767