---
apiVersion: v1
kind: Service
metadata:
  name: overseer
spec:
  type: ClusterIP
  ports:
    - port: 5055
      targetPort: 5055
      protocol: TCP
      name: overseer
  selector:
    app.kubernetes.io/component: overseer
    app.kubernetes.io/instance: overseer
    app.kubernetes.io/name: overseer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseer
  labels:
    app.kubernetes.io/component: overseer
    app.kubernetes.io/instance: overseer
    app.kubernetes.io/name: overseer
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: overseer
      app.kubernetes.io/name: overseer
      app.kubernetes.io/instance: overseer
  template:
    metadata:
      labels:
        app.kubernetes.io/component: overseer
        app.kubernetes.io/instance: overseer
        app.kubernetes.io/name: overseer
    spec:
      enableServiceLinks: true
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: sctx/overseerr:latest
          name: overseerr
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
          volumeMounts:
            - mountPath: /app/config
              name: data
              subPath: overseerr/config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: media-stack-data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseer
  labels:
    app.kubernetes.io/instance: overseer
    app.kubernetes.io/name: overseer
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "requests-test.galactica.host"
      secretName: "overseer-tls-certificate"
  rules:
    - host: "requests-test.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: overseer
                port:
                  number: 5055