---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: ClusterIP
  ports:
    - port: 32400
      targetPort: 32400
      protocol: TCP
      name: plex
  selector:
    app.kubernetes.io/component: plex
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app.kubernetes.io/component: plex
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: plex
      app.kubernetes.io/name: plex
      app.kubernetes.io/instance: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/component: plex
        app.kubernetes.io/instance: plex
        app.kubernetes.io/name: plex
    spec:
      enableServiceLinks: true
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: ghcr.io/linuxserver/plex:latest
          name: plex
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: plex/config
            - mountPath: /data/media
              name: nfs-vol
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: media-stack-data
        - name: nfs-vol
          nfs:
            server: 192.168.0.11
            path: /media
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "plex.galactica.host"
      secretName: "plex-tls-certificate"
  rules:
    - host: "plex.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400