apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-stack-data
spec:
  storageClassName: "nfs-csi"
  accessModes:
    - "ReadWriteMany"
  capacity:
    storage: 100Gi
  claimRef:
    name: media-stack-data
    namespace: media-stack

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-stack-data
spec:
  volumeName: "media-stack-data"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 100Gi