#TODO: increase size of disk
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media-stack-data-local
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: local-path
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: pvc-media-stack-data-local
    namespace: media-stack
  hostPath:
    path: /opt/k8s-pod-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media-stack-data-local
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  storageClassName: local-path
  volumeName: pv-media-stack-data-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tank-data
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  capacity:
    storage: 64Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    name: pvc-tank-data
    namespace: media-stack
  mountOptions:
    - hard
    - timeo=600
    - retrans=3
    - proto=tcp
    # - nfsvers=4.2
    - rsize=1048576
    - wsize=1048576
    - noresvport
    - noacl
    - nocto
    # - noatime
    # - nodiratime
  nfs:
    server: 192.168.0.11
    path: /export/tank/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-tank-data
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  capacity:
    storage: 64Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    name: pvc-media
    namespace: media-stack
  mountOptions:
    - hard
    - timeo=600
    - retrans=3
    - proto=tcp
    # - nfsvers=4.2
    - rsize=1048576
    - wsize=1048576
    - noresvport
    - noacl
    - nocto
    # - noatime
    # - nodiratime
  nfs:
    server: 192.168.0.11
    path: /export/media
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Ti
