apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media-stack-data-local
spec:
  storageClassName: local-path
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: pvc-media-stack-data-local
    namespace: media-stack
  hostPath:
    path: /opt/k8s-pod-storage

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media-stack-data-local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media-stack-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: pvc-media-stack-data
    namespace: media-stack
  mountOptions:
    - hard
    - timeo=600
    - retrans=3
    - proto=tcp
    - nfsvers=4.2
    - rsize=4096
    - wsize=4096
    - noacl
    - nocto
    - noatime
    - nodiratime
  nfs:
    server: 192.168.0.11
    path: /homelab-k8s/media-stack-config-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media-stack-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tank-data
spec:
  capacity:
    storage: 64Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    name: pvc-tank-data
    namespace: media-stack
  mountOptions:
    - hard
    - timeo=600
    - retrans=3
    - proto=tcp
    - nfsvers=4.2
    - rsize=4096
    - wsize=4096
    - noacl
    - nocto
    - noatime
    - nodiratime
  nfs:
    server: 192.168.0.11
    path: /tank/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-tank-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media
spec:
  capacity:
    storage: 64Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    name: pvc-media
    namespace: media-stack
  mountOptions:
    - hard
    - timeo=600
    - retrans=3
    - proto=tcp
    - nfsvers=4.2
    - rsize=4096
    - wsize=4096
    - noacl
    - nocto
    - noatime
    - nodiratime
  nfs:
    server: 192.168.0.11
    path: /media
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Ti
