---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: sabnzbd
  selector:
    app.kubernetes.io/component: sabnzbd
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/name: sabnzbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  labels:
    app.kubernetes.io/component: sabnzbd
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/name: sabnzbd
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: sabnzbd
      app.kubernetes.io/name: sabnzbd
      app.kubernetes.io/instance: sabnzbd
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sabnzbd
        app.kubernetes.io/instance: sabnzbd
        app.kubernetes.io/name: sabnzbd
    spec:
      enableServiceLinks: true
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: linuxserver/sabnzbd:latest
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: sabnzbd/config
            - mountPath: /data/usenet
              name: nfs-vol
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: sabnzbd
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: media-stack-data
        - name: nfs-vol
          nfs:
            server: 192.168.0.11
            path: /tank/data/usenet
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  labels:
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/name: sabnzbd
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "sabnzbd-test.galactica.host"
      secretName: "sabnzbd-tls-certificate"
  rules:
    - host: "sabnzbd-test.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: sabnzbd
                port:
                  number: 8080