---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  type: ClusterIP
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
      name: sonarr
  selector:
    app.kubernetes.io/component: sonarr
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/component: sonarr
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: sonarr
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/instance: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sonarr
        app.kubernetes.io/instance: sonarr
        app.kubernetes.io/name: sonarr
    spec:
      enableServiceLinks: true
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: linuxserver/sonarr:latest
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: sonarr/config
            - mountPath: /data
              name: nfs-vol
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 8989
            timeoutSeconds: 1
          name: sonarr
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 8989
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            tcpSocket:
              port: 8989
            timeoutSeconds: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: media-stack-data
        - name: nfs-vol
          nfs:
            server: 192.168.0.11
            path: /tank/data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "sonarr-test.galactica.host"
      secretName: "sonarr-tls-certificate"
  rules:
    - host: "sonarr-test.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989