---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  type: ClusterIP
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
      name: sonarr
  selector:
    app.kubernetes.io/component: sonarr
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/component: sonarr
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: sonarr
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/instance: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sonarr
        app.kubernetes.io/instance: sonarr
        app.kubernetes.io/name: sonarr
    spec:
      enableServiceLinks: true
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: linuxserver/sonarr:latest
          name: sonarr
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: sonarr/config
            - mountPath: /data
              name: tank-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media-stack-data
        - name: tank-data
          persistentVolumeClaim:
            claimName: pvc-tank-data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "sonarr.galactica.host"
      secretName: "sonarr-tls-certificate"
  rules:
    - host: "sonarr.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989