---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
spec:
  type: ClusterIP
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: tautulli
  selector:
    app.kubernetes.io/component: tautulli
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/name: tautulli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/component: tautulli
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/name: tautulli
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: tautulli
      app.kubernetes.io/name: tautulli
      app.kubernetes.io/instance: tautulli
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tautulli
        app.kubernetes.io/instance: tautulli
        app.kubernetes.io/name: tautulli
    spec:
      enableServiceLinks: true
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: ghcr.io/linuxserver/tautulli:latest
          name: tautulli
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
            - name: TZ
              value: America/Toronto
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: tautulli/config
            - mountPath: /data
              name: tank-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media-stack-data-local
        - name: tank-data
          persistentVolumeClaim:
            claimName: pvc-tank-data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/name: tautulli
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "tautulli.galactica.host"
      secretName: "tautulli-tls-certificate"
  rules:
    - host: "tautulli.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: tautulli
                port:
                  number: 8181