---
apiVersion: v1
kind: Service
metadata:
  name: wizarr
spec:
  type: ClusterIP
  ports:
    - port: 5690
      targetPort: 5690
      protocol: TCP
      name: wizarr
  selector:
    app.kubernetes.io/component: wizarr
    app.kubernetes.io/instance: wizarr
    app.kubernetes.io/name: wizarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
  labels:
    app.kubernetes.io/component: wizarr
    app.kubernetes.io/instance: wizarr
    app.kubernetes.io/name: wizarr
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: wizarr
      app.kubernetes.io/name: wizarr
      app.kubernetes.io/instance: wizarr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: wizarr
        app.kubernetes.io/instance: wizarr
        app.kubernetes.io/name: wizarr
    spec:
      enableServiceLinks: true
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: ghcr.io/wizarrrr/wizarr:latest
          name: wizarr
          env:
            - name: TZ
              value: America/Toronto
          volumeMounts:
            - mountPath: /data/database
              name: data
              subPath: wizarr/database
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media-stack-data-local

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizarr
  labels:
    app.kubernetes.io/instance: wizarr
    app.kubernetes.io/name: wizarr
  annotations:
    cert-manager.io/cluster-issuer: ssl-prod
    external-dns.alpha.kubernetes.io/target: "homelab-tunnel.galactica.host"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "wizarr.galactica.host"
      secretName: "wizarr-tls-certificate"
  rules:
    - host: "wizarr.galactica.host"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: wizarr
                port:
                  number: 5690