---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: smb.csi.k8s.io
reclaimPolicy: {{ .Values.reclaimPolicy }}
parameters:
  # On Windows, "*.default.svc.cluster.local" could not be recognized by csi-proxy
  source: {{ .Values.source }}
  # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
  # with PV name under source
  csi.storage.k8s.io/provisioner-secret-name: smbcreds
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: smbcreds
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0750
  - file_mode=0750
  - uid=1000
  - gid=100
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino  # required to prevent data corruption