argo-cd:
  server:
    metrics: &metrics
      enabled: false  # Change this to enable metrics
      serviceMonitor:
        enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
argocd-apps:
  applicationsets:
    root:
      generators:
        - git:
            repoURL: &repoURL https://github.com/adamazoulay/homelab-proxmox-k8s
            revision: &revision main
            directories:
              - path: system/*
              - path: platform/*
              - path: apps/*
      template:
        metadata:
          name: '{{path.basename}}'
        spec:
          destination:
            name: in-cluster
            namespace: '{{path.basename}}'
          project: default  # TODO
          source:
            repoURL: *repoURL
            path: '{{path}}'
            targetRevision: *revision
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            retry:
              limit: 10
              backoff:
                duration: 1m
                factor: 2
                maxDuration: 16m
            syncOptions:
              - CreateNamespace=true
              - ApplyOutOfSyncOnly=true
              - ServerSideApply=true
