argo-cd:
  server:
    metrics: &metrics
      enabled: false  # Change this to enable metrics
      serviceMonitor:
        enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
argocd-apps:
  applicationsets:
    root:
      generators:
        - git:
            repoURL: &repoURL https://github.com/adamazoulay/homelab-proxmox-k8s
            revision: &revision master
            directories:
              - path: system/*
              - path: platform/*
              - path: apps/*
      template:
        spec:
          source:
            repoURL: *repoURL
            targetRevision: *revision
